import React from 'react';
import { ResultData, ChatMessage, AppMode } from '../types';
import Spinner from './Spinner';
import { SparklesIcon, UserIcon, BotIcon } from './icons';

interface ResultDisplayProps {
  isLoading: boolean;
  result: ResultData | null;
  chatHistory: ChatMessage[];
  mode: AppMode;
}

const WelcomeMessage: React.FC = () => (
    <div className="text-center text-slate-500 flex flex-col items-center justify-center h-full gap-4">
        <SparklesIcon className="w-16 h-16 text-blue-500"/>
        <h2 className="text-2xl font-bold text-slate-700">Welcome to the Creative Suite</h2>
        <p className="max-w-md">Select a mode and enter a prompt below to get started. Let your creativity flow!</p>
    </div>
);

const ChatBubble: React.FC<{ message: ChatMessage }> = ({ message }) => {
    const isUser = message.role === 'user';
    
    return (
        <div className={`flex items-start gap-3 w-full max-w-2xl mx-auto ${isUser ? 'justify-end' : 'justify-start'}`}>
            {!isUser && (
                <div className="w-8 h-8 rounded-full bg-slate-200 flex items-center justify-center flex-shrink-0">
                    <BotIcon className="w-5 h-5 text-slate-500" />
                </div>
            )}
            <div className={`px-4 py-3 rounded-2xl max-w-[80%] ${isUser ? 'bg-blue-600 text-white rounded-br-lg' : 'bg-white text-slate-800 rounded-bl-lg shadow-sm border border-slate-200'}`}>
                <p className="whitespace-pre-wrap leading-relaxed">{message.content}</p>
            </div>
             {isUser && (
                <div className="w-8 h-8 rounded-full bg-slate-700 flex items-center justify-center flex-shrink-0">
                    <UserIcon className="w-5 h-5 text-slate-200" />
                </div>
            )}
        </div>
    )
};


const ResultDisplay: React.FC<ResultDisplayProps> = ({ isLoading, result, chatHistory, mode }) => {
  const isChatMode = mode === AppMode.Agent || mode === AppMode.FineTuned;

  if (isLoading && chatHistory.length === 0) {
    return <div className="flex justify-center items-center h-full"><Spinner /></div>;
  }

  if (!result && chatHistory.length === 0) {
    return <WelcomeMessage />;
  }

  if (isChatMode) {
    return (
        <div className="flex flex-col gap-4 pb-4">
            {chatHistory.map((msg, index) => (
                <ChatBubble key={index} message={msg} />
            ))}
            {isLoading && chatHistory.length > 0 && (
                <div className="self-start ml-12">
                     <div className="w-16 h-8 bg-white rounded-2xl rounded-bl-lg shadow-sm border border-slate-200 flex items-center justify-center">
                        <div className="flex gap-1">
                           <span className="w-2 h-2 rounded-full bg-slate-400 animate-bounce delay-0"></span>
                           <span className="w-2 h-2 rounded-full bg-slate-400 animate-bounce delay-150"></span>
                           <span className="w-2 h-2 rounded-full bg-slate-400 animate-bounce delay-300"></span>
                        </div>
                     </div>
                </div>
            )}
        </div>
    );
  }

  return (
    <div className="max-w-4xl mx-auto w-full animate-fade-in">
      {result?.type === 'image' && (
        <div className="p-4 bg-black/10 rounded-lg">
          <img
            src={`data:image/png;base64,${result.content}`}
            alt="Generated by Gemini"
            className="w-full max-w-lg mx-auto rounded-md shadow-2xl"
          />
        </div>
      )}
      {result?.type === 'text' && (
        <div className="bg-white p-4 sm:p-6 rounded-lg shadow-md border border-slate-200">
          <p className="text-slate-700 whitespace-pre-wrap leading-relaxed">{result.content}</p>
        </div>
      )}
      {result?.type === 'error' && (
        <div className="bg-red-100 border border-red-300 p-4 rounded-lg">
          <h3 className="font-bold text-red-700 mb-2">An Error Occurred</h3>
          <p className="text-red-600">{result.content}</p>
        </div>
      )}
    </div>
  );
};

export default ResultDisplay;